language: groovy

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc wkhtmltopdf

script: ./gradlew clean build cobertura

jdk:
  - oraclejdk7
  - openjdk7

env: TERM=dumb

after_success: ./gradlew coveralls
